name: dmart_android_flutter
description: Flutter skeleton for dmart
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  get_storage: ^2.1.1
  get: ^4.6.5
  awesome_dio_interceptor: ^1.0.0
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
    - assets/images/login/
  fonts:
  - family: KanunAR
    fonts:
      - asset: assets/fonts/kanun_ar_lt_black.otf
        weight: 900
      - asset: assets/fonts/kanun_ar_lt_bold.otf
        weight: 700
      - asset: assets/fonts/kanun_ar_lt_extra_light.otf
        weight: 200
      - asset: assets/fonts/kanun_ar_lt_hairline.otf
        weight: 100
      - asset: assets/fonts/kanun_ar_lt_heavy.otf
        weight: 800
      - asset: assets/fonts/kanun_ar_lt_light.otf
        weight: 300
      - asset: assets/fonts/kanun_ar_lt_medium.otf
        weight: 500
      - asset: assets/fonts/kanun_ar_lt_regular.otf
        weight: 400
      - asset: assets/fonts/kanun_ar_lt_thin.otf
        weight: 100

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
